e8c731b5-9fb5-4a95-93eb-94528c0ef816apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    prometheus.io.scrape: "false"
  creationTimestamp: "2022-03-18T14:10:38Z"
  generation: 2
  labels:
    faas_function: production-19e7ec92-8b48-4f89-bf18-5f7c4c1be236-4
  name: production-19e7ec92-8b48-4f89-bf18-5f7c4c1be236-4
  namespace: openfaas-fn
  resourceVersion: "15889338254"
  uid: 62001ff6-6d82-4952-85e2-2250b1ee695c
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      faas_function: production-19e7ec92-8b48-4f89-bf18-5f7c4c1be236-4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io.scrape: "false"
      creationTimestamp: null
      labels:
        faas_function: production-19e7ec92-8b48-4f89-bf18-5f7c4c1be236-4
      name: production-19e7ec92-8b48-4f89-bf18-5f7c4c1be236-4
    spec:
      containers:
      - image: registry.gitlab.com/lenra/platform/lenra-ci/production/19e7ec92-8b48-4f89-bf18-5f7c4c1be236:4
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /_/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        name: production-19e7ec92-8b48-4f89-bf18-5f7c4c1be236-4
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          readOnlyRootFilesystem: false
          runAsUser: 12000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      imagePullSecrets:
      - name: gitlab-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-03-18T14:10:38Z"
    lastUpdateTime: "2022-03-18T14:10:55Z"
    message: ReplicaSet "production-19e7ec92-8b48-4f89-bf18-5f7c4c1be236-4-778df4b55f"
      has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-12-16T08:26:33Z"
    lastUpdateTime: "2022-12-16T08:26:33Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
